version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: esg-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emissions_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    restart: unless-stopped

volumes:
  pgdata: